@Library('argocd_shared_lib@master') _

pipeline {
  agent { label 'vm-1' }  // Disable default agent to force each stage to pick explicitly

  environment {
    DOCKER_IMAGE = 'yossefazozz/argocd_lab'  // Docker image name with build number
    DOCKER_CREDENTIALS_ID = '39efdf06-f686-4219-8117-a9efd32f0c16'  // Jenkins credential ID
  }

  stages {

    stage('Build') {
      steps {
        git branch: 'main', url: 'https://github.com/Ibrahim-Adel15/Jenkins_App.git'
        buildApp()
      }
    }

    stage('Docker') {
        // Docker must run on the agent with Docker installed
      steps {
        buildAndPushImage(DOCKER_IMAGE, DOCKER_CREDENTIALS_ID)
      }
    }

    

    stage('edit_deployment') {
        // kubectl runs on the controller
      steps {
        edit_deployment_argocd(DOCKER_IMAGE)
      }
    }

    stage('push_to_argo') {
        // kubectl runs on the controller
      steps {
        push_to_argo(DOCKER_IMAGE)
      }
    }

  }
}
